### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by christianesperar** [zphalcon/phalcon-tip#9]

**Comment by duythien** [comment]
Hey
Curently it painator following  like http://getbootstrap.com/components/#pagination-pager

**Comment by christianesperar** [comment]
The current implementation is pager. I think pagination is much better and add awesomeness on this site.

**Comment by duythien** [comment]
yes,  I will make later

**Comment by duythien** [comment]
If you want to use it, you can take look here http://phalcontip.com/discussion/37/how-to-pagination-for-multipage-component-in-phalcon
